
--My SQL
CREATE SCHEMA pruebas;

CREATE TABLE pruebas.serialized_dag(
    dag_id TEXT,
    fileloc TEXT,
    dag_hash TEXT,
    last_updated DATETIME
)

SELECT * FROM `pruebas`.`serialized_dag` LIMIT 1000;

CREATE TABLE pruebas.localidades(
ENTIDAD INT,
NOMBREENTIDAD TEXT,
MUNICIPIO INT,
NOMBREMUNICIPIO TEXT,
LOCALIDAD INT,
NOMBRELOCALIDAD TEXT,
TIPO TEXT)

--PostgreSQL

CREATE TABLE public.localidades(
ENTIDAD INT,
NOMBREENTIDAD TEXT,
MUNICIPIO INT,
NOMBREMUNICIPIO TEXT,
LOCALIDAD INT,
NOMBRELOCALIDAD TEXT,
TIPO TEXT)