
--My SQL
CREATE SCHEMA pruebas;

CREATE TABLE pruebas.serialized_dag(
    dag_id TEXT,
    fileloc TEXT,
    dag_hash TEXT,
    last_updated DATETIME
);

CREATE TABLE pruebas.localidades(
ENTIDAD INT,
NOMBREENTIDAD TEXT,
MUNICIPIO INT,
NOMBREMUNICIPIO TEXT,
LOCALIDAD INT,
NOMBRELOCALIDAD TEXT,
TIPO TEXT);

CREATE TABLE pruebas.lighthouse(
Fecha TEXT,
Pagina TEXT,
Indicador TEXT,
Resultado TEXT,
Meta FLOAT,
ispositivo TEXT,
Red TEXT,
Cache TEXT);

--PostgreSQL

CREATE TABLE public.localidades(
ENTIDAD INT,
NOMBREENTIDAD TEXT,
MUNICIPIO INT,
NOMBREMUNICIPIO TEXT,
LOCALIDAD INT,
NOMBRELOCALIDAD TEXT,
TIPO TEXT)